export const ANALYTICS_EVENTS = {
  USER_LOGIN: 'USER_LOGIN',
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGOUT: 'USER_LOGOUT',
  INTERNSHIP_VIEW: 'INTERNSHIP_VIEW',
  INTERNSHIP_APPLY_CLICK: 'INTERNSHIP_APPLY_CLICK',
  INTERNSHIP_SAVE: 'INTERNSHIP_SAVE',
  INTERNSHIP_UNSAVE: 'INTERNSHIP_UNSAVE',
  PIPELINE_RUN: 'PIPELINE_RUN',
} as const;
