"""initial_schema

Revision ID: 90f8c3005371
Revises:
Create Date: 2026-07-08 09:58:33.411423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90f8c3005371"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "internships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "company",
            sa.String(length=100),
            nullable=False,
            comment="Company name as scraped from the source",
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False,
            comment="Job or internship title",
        ),
        sa.Column(
            "location",
            sa.String(length=150),
            nullable=True,
            comment="Geographic location or region, if available",
        ),
        sa.Column(
            "employment_type",
            sa.String(length=50),
            nullable=False,
            comment="Employment classification, e.g. internship or full-time",
        ),
        sa.Column(
            "work_mode",
            sa.String(length=50),
            nullable=False,
            comment="Work arrangement, e.g. remote, hybrid, or on-site",
        ),
        sa.Column(
            "url",
            sa.String(length=500),
            nullable=False,
            comment="Canonical URL used for deduplication",
        ),
        sa.Column(
            "posted_date",
            sa.Date(),
            nullable=True,
            comment="Date the listing was originally posted, if known",
        ),
        sa.Column(
            "deadline",
            sa.Date(),
            nullable=True,
            comment="Application deadline, if published",
        ),
        sa.Column(
            "stipend",
            sa.String(length=100),
            nullable=True,
            comment="Stipend or compensation text as shown on the source",
        ),
        sa.Column(
            "skills",
            sa.Text(),
            nullable=True,
            comment="Skills or requirements extracted from the listing",
        ),
        sa.Column(
            "source",
            sa.String(length=100),
            nullable=False,
            comment="Scraper or platform identifier that found this listing",
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False,
            comment="Pipeline status, e.g. new, active, or archived",
        ),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this listing was first discovered",
        ),
        sa.Column(
            "last_seen",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this listing was last observed in a scrape",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this row was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC timestamp when this row was last modified",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("internships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_internships_company"), ["company"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_internships_title"), ["title"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_internships_url"), ["url"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("internships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_internships_url"))
        batch_op.drop_index(batch_op.f("ix_internships_title"))
        batch_op.drop_index(batch_op.f("ix_internships_company"))

    op.drop_table("internships")
    # ### end Alembic commands ###
