"""Add saved_jobs table

Revision ID: 2fd16d17ca5b
Revises: 6edd2f369dcb
Create Date: 2026-07-12 12:41:21.871870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fd16d17ca5b"
down_revision: Union[str, None] = "6edd2f369dcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("internship_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["internship_id"], ["internships.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "internship_id", name="uq_user_internship_saved"
        ),
    )
    with op.batch_alter_table("saved_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_saved_jobs_internship_id"), ["internship_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_saved_jobs_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("saved_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_jobs_user_id"))
        batch_op.drop_index(batch_op.f("ix_saved_jobs_internship_id"))

    op.drop_table("saved_jobs")
    # ### end Alembic commands ###
